### ISSUE TITLE
Zigzag depending on frame rate?

### ISSUE THREAD

**Issue by Siphalor** [Mioriarty/Protect#3]
It seems the zigzag is depending on the frame rate, not on the time. So if you're playing on a powerful device the zigzag obstacles are glitching weirdly.

Very weird looking menus for the desktop version by the way.

**Comment by Mioriarty** [comment]
This game will be a mobile game, so I don't care about the menu in the desktop version. The executive file in the release was just a chance for the iOS-user to try my game, but they have to deal with weird looking proportions
